-- Storage Buckets & Policies

-- 1. Create 'artifacts' bucket (Private)
insert into storage.buckets
  (id, name, public)
values
  ('artifacts', 'artifacts', false)
on conflict (id) do nothing;

-- 2. Policies
-- Upload: Admin Only
create policy "Admins can upload artifacts"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'artifacts' 
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Download/Select: Admin Only (Strict by default)
-- (Or implemented via Signed URLs generated by Admin backend)
create policy "Admins can view artifacts"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'artifacts'
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Delete: Admin Only
create policy "Admins can delete artifacts"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'artifacts'
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );
